---
title: "Conferences"
editor: 
  markdown: 
    wrap: 72
---



### 2026
- <span style="color: #f96211;">**April — IRSPM2026 (Edith Cowan University, Australia)**</span>  
  Yanto Chandra, **Jianxiang Tan** — "Will Future Employees Prefer ‘AI as Street-level Managers’ in the Workplace?"


- <span style="color: #f96211;">**Feb — PUBSIC2026 (Corvinus University of Budapest, Hungary)**</span>  
  **Jianxiang Tan**, Guanru Zhang, Helen Bao, & Yanto Chandra — "Public Blame in Algorithmic Welfare Services: Citizens’ Allocation of Responsibility Across the Network of Actors."

### 2025
- <span style="color: #f96211;">**Jun — PMRC2025 (Seoul National University, Korea)**</span>  
  Yanto Chandra & **Jianxiang Tan** — "Mapping the Landscape of Public Sector Innovation: A Topic Modeling Approach."

- <span style="color: #f96211;">**Apr — IRSPM2025 (University of Bologna, Italy)**</span>  
  **Jianxiang Tan** & Yanto Chandra — "Artificial Intelligence Recommendations and Citizen Compliance: A Public Value Creation Perspective."
 
  Yanto Chandra, Yiyun Luo, & **Jianxiang Tan** — "Trust Me, I am Almost a Doctor: Uncertainty in AI-mediated Doctor-Patient Interactions."

  Yanto Chandra & **Jianxiang Tan** — "Probing the Past to Chart Plausible Futures in Public Sector Innovation: Toward a Design Science in AI-Driven Public Administration."

### 2024
- <span style="color: #f96211;">**Nov — AI & Public Policy International Conference (Nanyang Technological University, Singapore)**</span>  
  **Jianxiang Tan** & Yanto Chandra — "Artificial Intelligence Recommendations and Citizen Compliance: A Public Value Creation Perspective."

  Yanto Chandra & **Jianxiang Tan** — "Predicting Public Service Innovation Outcomes using Generative Artificial Intelligence."

